// Treatment pages supplied by the client (Sleep_Anaesthesia_Treatment_Pages.docx,
// Oct 2026). Titles, summaries and body text are used exactly as supplied; the
// body HTML mirrors the document's headings, lists, bold labels and links.
// Pages 1–4 had no summary line, so their first sentence is used.
import type { Treatment } from '../types'

export const TREATMENTS: Treatment[] = [
  {
    title: "Wisdom teeth removal under IV sedation",
    menuLabel: "Wisdom teeth",
    slug: "wisdom-teeth",
    summary: "Having your wisdom teeth out can feel daunting, and IV sedation makes the experience much easier.",
    body: "<p>Having your wisdom teeth out can feel daunting, and IV sedation makes the experience much easier. The medication goes straight into a vein, so it works within minutes. You'll be deeply relaxed and drowsy, and most patients remember little or nothing of the procedure afterwards.</p><p>Because it's given continuously, the sedation is adjusted to your needs throughout the procedure. That usually means more than one wisdom tooth can be removed in a single visit, often all four. A dedicated anaesthetist stays with you the whole time, monitoring your breathing, heart rate and oxygen levels, so your dentist can focus entirely on the surgery.</p><p>Recovery from IV sedation is generally quicker than from a general anaesthetic, and you'll be able to go home the same day with a responsible adult. It's a good option for anxious patients, complex or impacted teeth, and anyone who would rather not be aware of the procedure.</p><p><em>Suitability for IV sedation is assessed individually. As with any procedure, there are risks, which your anaesthetist will discuss with you beforehand.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Dental treatment under IV sedation for a strong gag reflex",
    menuLabel: "Strong gag reflex",
    slug: "gag-reflex",
    summary: "For some people, a strong gag reflex makes even a routine check-up hard, and longer treatment can feel impossible.",
    body: "<p>For some people, a strong gag reflex makes even a routine check-up hard, and longer treatment can feel impossible. Gagging is an automatic reflex, not something you can simply control, and it can put off care you need.</p><p>IV sedation works directly on that reflex. We give a combination of anaesthetic and opioid-based medications through a vein. Together they blunt and reduce the gag reflex while keeping you deeply relaxed and drowsy. Your dentist can then carry out impressions, fillings, crowns or extractions comfortably, without having to keep stopping. Most patients remember little of the appointment afterwards.</p><p>The medications are adjusted throughout your treatment. That often means several procedures can be done in one longer visit, so you need fewer appointments overall. A dedicated anaesthetist stays with you the whole time and monitors your breathing, heart rate and oxygen levels, which leaves your dentist free to focus on your teeth.</p><p>You'll go home the same day with a responsible adult.</p><p><em>Suitability for IV sedation is assessed individually. As with any procedure, there are risks, which your anaesthetist will discuss with you beforehand.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Dental implants under IV sedation",
    menuLabel: "Dental implants",
    slug: "dental-implants",
    summary: "Dental implant surgery can mean a long appointment, with drilling, pressure and vibration that some patients find hard to sit through awake.",
    body: "<p>Dental implant surgery can mean a long appointment, with drilling, pressure and vibration that some patients find hard to sit through awake. IV sedation lets you have the treatment you need while feeling relaxed.</p><p>We give a combination of anaesthetic and opioid-based medications through a vein. You'll feel deeply relaxed and drowsy within minutes, and the medications help reduce discomfort during the procedure. Most patients remember little or nothing of the surgery afterwards, including the noise and the sensations that often cause the most anxiety.</p><p>The medications are adjusted continuously throughout your procedure. A dedicated anaesthetist stays with you the whole time and monitors your breathing, heart rate and oxygen levels, which leaves your dentist free to focus on placing your implant.</p><h2>When a general anaesthetic may be better</h2><p>For multiple implants or more complex implant surgery, such as full-arch treatment, bone grafting or sinus lifts, a general anaesthetic (GA) may be better suited. Under a GA you're fully asleep for the whole procedure, so your dentist can complete longer and more involved work in a single visit. Your anaesthetist will talk you through which option suits your treatment best.</p><p>With either option, you'll go home the same day with a responsible adult.</p><p><em>Suitability for IV sedation or general anaesthesia is assessed individually. As with any procedure, there are risks, which your anaesthetist will discuss with you beforehand.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Tooth extractions under IV sedation",
    menuLabel: "Tooth extractions",
    slug: "extractions",
    summary: "Having a tooth out is one of the most common reasons people put off seeing the dentist.",
    body: "<p>Having a tooth out is one of the most common reasons people put off seeing the dentist. The pressure, the sounds and the thought of the procedure itself can all make it hard to face, even when the tooth is causing pain. IV sedation lets you have the extraction done while feeling calm and relaxed.</p><p>We give a combination of anaesthetic and opioid-based medications through a vein. You'll feel deeply relaxed and drowsy within minutes, and the medications help reduce discomfort during the procedure. Most patients remember little or nothing of the extraction afterwards.</p><p>The medications are adjusted throughout your procedure, so more than one tooth can often be removed in a single visit. A dedicated anaesthetist stays with you the whole time and monitors your breathing, heart rate and oxygen levels, which leaves your dentist free to focus on your treatment.</p><h2>When a general anaesthetic may be better</h2><p>For multiple or complex extractions, such as a full clearance or surgically difficult teeth, a general anaesthetic (GA) may be better suited. Under a GA you're fully asleep for the whole procedure. Your anaesthetist will talk you through which option suits your treatment best.</p><p>With either option, you'll go home the same day with a responsible adult.</p><p><em>Suitability for IV sedation or general anaesthesia is assessed individually. As with any procedure, there are risks, which your anaesthetist will discuss with you beforehand.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Sedation for Full-Arch Implant Treatment (All-on-4®)",
    menuLabel: "All-on-4® (full arch)",
    slug: "all-on-4",
    summary: "Anaesthesia for full-arch implant treatment, including All-on-4®, delivered by a specialist anaesthetist in your dental clinic.",
    body: "<h2>Full-arch treatment is a big day</h2><p>Full-arch implant treatment, such as All-on-4®, usually combines extractions, implant placement and a temporary bridge in one long appointment. Many patients prefer to be sedated for the whole procedure. Sleep Anaesthesia brings the full anaesthetic setup to your implant clinic, so the surgery can go ahead where your treatment was planned.</p><h2>Sedation or general anaesthesia</h2><p>We provide <a href=\"/iv-sedation\">IV sedation</a> for full-arch implant procedures, and <a href=\"/general-anaesthesia\">general anaesthesia</a> in clinics that meet credentialing and accreditation requirements. Because full-arch treatment is long and involved, we recommend general anaesthesia for most patients having this procedure. Your anaesthetist will discuss the best option for you. A FANZCA specialist anaesthetist and an anaesthetic nurse stay with you throughout the procedure and recovery.</p><h2>Possible benefits of anaesthesia for full-arch surgery</h2><p>Having your surgery under sedation or general anaesthesia may offer benefits for both you and your surgical team:</p><ul><li><strong>Better mouth opening:</strong> with your jaw muscles relaxed, your surgeon may have better access for longer periods without you needing to hold your mouth open.</li><li><strong>Improved bite assessment:</strong> relaxed jaw muscles may help your surgeon assess and guide your bite more accurately when fitting your new teeth.</li><li><strong>Specialist pain relief:</strong> your anaesthetist can give strong pain-relieving medications during the procedure to help keep you comfortable during surgery and in early recovery.</li><li><strong>Less swelling and bruising:</strong> medications given by your anaesthetist may help reduce inflammation, swelling and bruising after surgery.</li></ul><p>Individual results vary, and your anaesthetist will discuss what to expect in your case.</p><h2>Preparing and recovering</h2><ul><li>Fast as instructed: no food for 6 hours beforehand, and clear fluids only up to 2 hours before.</li><li>Arrange a responsible adult to take you home and stay with you for the rest of the day and night.</li><li>Do not drive, drink alcohol or sign legal documents for 24 hours afterwards.</li></ul><p>Full instructions, and answers to payment and Medicare questions, are on our <a href=\"/patients\">patient information page</a>.</p><p><em>All-on-4® is a registered trademark of Nobel Biocare. Sleep Anaesthesia is not affiliated with Nobel Biocare.</em></p><p><em>Suitability for sedation is assessed individually. Any surgical or invasive procedure carries risks; before proceeding, you should seek a second opinion from an appropriately qualified health practitioner.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Sedation for Full-Arch / All-on-X Surgery",
    menuLabel: "All-on-X (full arch)",
    slug: "all-on-x",
    summary: "Specialist anaesthesia for full-arch and All-on-X implant surgery, one of the procedures we support most often in dental clinics.",
    body: "<h2>Anaesthesia for full-arch surgery</h2><p>Full-arch implant surgery, often called All-on-X, replaces a whole arch of teeth using as many implants as your surgeon plans for your jaw. It usually combines extractions, implant placement and a temporary bridge in one long appointment. A single case can make up a whole operating session for a clinic.</p><h2>How we support the procedure</h2><p>A FANZCA specialist anaesthetist provides <a href=\"/iv-sedation\">IV sedation</a>, or <a href=\"/general-anaesthesia\">general anaesthesia</a> in clinics that meet credentialing and accreditation requirements. Because of the length and complexity of the surgery, we recommend general anaesthesia for most patients having this procedure. Your anaesthetist will discuss the best option for you.</p><h2>Possible benefits of anaesthesia for full-arch surgery</h2><p>Having your surgery under sedation or general anaesthesia may offer benefits for both you and your surgical team:</p><ul><li><strong>Better mouth opening:</strong> with your jaw muscles relaxed, your surgeon may have better access for longer periods without you needing to hold your mouth open.</li><li><strong>Improved bite assessment:</strong> relaxed jaw muscles may help your surgeon assess and guide your bite more accurately when fitting your new teeth.</li><li><strong>Specialist pain relief:</strong> your anaesthetist can give strong pain-relieving medications during the procedure to help keep you comfortable during surgery and in early recovery.</li><li><strong>Less swelling and bruising:</strong> medications given by your anaesthetist may help reduce inflammation, swelling and bruising after surgery.</li></ul><p>Individual results vary, and your anaesthetist will discuss what to expect in your case.</p><p>Dental clinics: see <a href=\"/clinics\">how mobile sedation works for your practice</a>.</p><h2>Preparing and recovering</h2><ul><li>Fast as instructed: no food for 6 hours beforehand, and clear fluids only up to 2 hours before.</li><li>Arrange a responsible adult to take you home and stay with you for the rest of the day and night.</li><li>Do not drive, drink alcohol or sign legal documents for 24 hours afterwards.</li></ul><p>Full instructions, and answers to payment and Medicare questions, are on our <a href=\"/patients\">patient information page</a>.</p><p><em>Suitability for sedation is assessed individually. Any surgical or invasive procedure carries risks; before proceeding, you should seek a second opinion from an appropriately qualified health practitioner.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Sedation for Dental Anxiety and Phobia",
    menuLabel: "Dental anxiety & phobia",
    slug: "dental-anxiety",
    summary: "Specialist sedation for patients who find dental treatment stressful, delivered in your dental clinic.",
    body: "<h2>You're not alone</h2><p>Dental anxiety is common, and for some people it's strong enough to put off treatment for years. Sedation lets you have the care you need while feeling calm and relaxed. Most patients remember little of the appointment afterwards.</p><h2>Sedation or general anaesthesia</h2><p>A FANZCA specialist anaesthetist provides <a href=\"/iv-sedation\">IV sedation</a> for most patients, or <a href=\"/general-anaesthesia\">general anaesthesia</a> in clinics that meet credentialing and accreditation requirements, for severe anxiety or longer treatment. Your anaesthetist will discuss the best option for you.</p><h2>Fewer appointments</h2><p>Because the sedation is adjusted throughout your treatment, several procedures can often be done in one visit, so you need fewer appointments overall.</p><h2>Preparing and recovering</h2><ul><li>Fast as instructed: no food for 6 hours beforehand, and clear fluids only up to 2 hours before.</li><li>Arrange a responsible adult to take you home and stay with you for the rest of the day and night.</li><li>Do not drive, drink alcohol or sign legal documents for 24 hours afterwards.</li></ul><p>Full instructions, and answers to payment and Medicare questions, are on our <a href=\"/patients\">patient information page</a>.</p><p><em>Suitability for sedation is assessed individually. Any surgical or invasive procedure carries risks; before proceeding, you should seek a second opinion from an appropriately qualified health practitioner.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Sedation for Root Canal Treatment",
    menuLabel: "Root canal treatment",
    slug: "root-canal",
    summary: "Anaesthesia for root canal treatment, delivered by a specialist anaesthetist in your dental clinic.",
    body: "<h2>A long appointment made easier</h2><p>Root canal treatment can mean a long appointment with your mouth open, and it's one of the procedures anxious patients find hardest to face. Sedation helps you stay relaxed and comfortable for the whole appointment, so your dentist or endodontist can work steadily without stopping.</p><h2>Sedation or general anaesthesia</h2><p>A FANZCA specialist anaesthetist provides <a href=\"/iv-sedation\">IV sedation</a> for most patients, or <a href=\"/general-anaesthesia\">general anaesthesia</a> in clinics that meet credentialing and accreditation requirements, which may suit multiple or complex root canals. Your anaesthetist will discuss the best option for you.</p><h2>Preparing and recovering</h2><ul><li>Fast as instructed: no food for 6 hours beforehand, and clear fluids only up to 2 hours before.</li><li>Arrange a responsible adult to take you home and stay with you for the rest of the day and night.</li><li>Do not drive, drink alcohol or sign legal documents for 24 hours afterwards.</li></ul><p>Full instructions, and answers to payment and Medicare questions, are on our <a href=\"/patients\">patient information page</a>.</p><p><em>Suitability for sedation is assessed individually. Any surgical or invasive procedure carries risks; before proceeding, you should seek a second opinion from an appropriately qualified health practitioner.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Sedation for Bone Grafts and Sinus Lifts",
    menuLabel: "Bone grafts & sinus lifts",
    slug: "bone-grafts-sinus-lifts",
    summary: "Specialist anaesthesia for bone grafting and sinus lift procedures, often done before dental implants.",
    body: "<h2>Preparing your jaw for implants</h2><p>Bone grafts and sinus lifts build up the jaw so implants can be placed securely. These procedures can involve drilling, pressure and longer surgery times. Sedation helps you stay relaxed and comfortable, and grafting can often be combined with implant placement or other treatment in one visit.</p><h2>Sedation or general anaesthesia</h2><p>A FANZCA specialist anaesthetist provides <a href=\"/iv-sedation\">IV sedation</a> for single-site grafts. For larger or combined grafting procedures, <a href=\"/general-anaesthesia\">general anaesthesia</a> may be better suited, in clinics that meet credentialing and accreditation requirements. Your anaesthetist will discuss the best option for you.</p><h2>Preparing and recovering</h2><ul><li>Fast as instructed: no food for 6 hours beforehand, and clear fluids only up to 2 hours before.</li><li>Arrange a responsible adult to take you home and stay with you for the rest of the day and night.</li><li>Do not drive, drink alcohol or sign legal documents for 24 hours afterwards.</li></ul><p>Full instructions, and answers to payment and Medicare questions, are on our <a href=\"/patients\">patient information page</a>.</p><p><em>Suitability for sedation is assessed individually. Any surgical or invasive procedure carries risks; before proceeding, you should seek a second opinion from an appropriately qualified health practitioner.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Sedation for Full-Mouth Rehabilitation",
    menuLabel: "Full-mouth rehabilitation",
    slug: "full-mouth-rehabilitation",
    summary: "Anaesthesia for extensive restorative treatment, including multiple crowns, veneers and fillings.",
    body: "<h2>More done in one visit</h2><p>Full-mouth rehabilitation restores many teeth in a planned course of treatment. Under sedation or general anaesthesia, much of this work can often be done in one longer session instead of many separate appointments. That can reduce time off work and the stress of repeated visits.</p><h2>Sedation or general anaesthesia</h2><p>A FANZCA specialist anaesthetist provides <a href=\"/iv-sedation\">IV sedation</a>, or <a href=\"/general-anaesthesia\">general anaesthesia</a> in clinics that meet credentialing and accreditation requirements. General anaesthesia is often better suited to very long sessions. Your anaesthetist will discuss the best option for you.</p><h2>Preparing and recovering</h2><ul><li>Fast as instructed: no food for 6 hours beforehand, and clear fluids only up to 2 hours before.</li><li>Arrange a responsible adult to take you home and stay with you for the rest of the day and night.</li><li>Do not drive, drink alcohol or sign legal documents for 24 hours afterwards.</li></ul><p>Full instructions, and answers to payment and Medicare questions, are on our <a href=\"/patients\">patient information page</a>.</p><p><em>Suitability for sedation is assessed individually. Any surgical or invasive procedure carries risks; before proceeding, you should seek a second opinion from an appropriately qualified health practitioner.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Sedation for Gum Surgery",
    menuLabel: "Gum surgery",
    slug: "gum-surgery",
    summary: "Specialist anaesthesia for periodontal surgery, including gum grafts, flap surgery and crown lengthening.",
    body: "<h2>Comfortable periodontal treatment</h2><p>Gum surgery treats advanced gum disease, restores receding gums or prepares teeth for restorations. Sedation helps you stay relaxed and comfortable during the procedure, and your periodontist can work without interruption.</p><h2>Sedation or general anaesthesia</h2><p>A FANZCA specialist anaesthetist provides <a href=\"/iv-sedation\">IV sedation</a> for most patients, or <a href=\"/general-anaesthesia\">general anaesthesia</a> in clinics that meet credentialing and accreditation requirements, which may suit extensive or multi-site surgery. Your anaesthetist will discuss the best option for you.</p><h2>Preparing and recovering</h2><ul><li>Fast as instructed: no food for 6 hours beforehand, and clear fluids only up to 2 hours before.</li><li>Arrange a responsible adult to take you home and stay with you for the rest of the day and night.</li><li>Do not drive, drink alcohol or sign legal documents for 24 hours afterwards.</li></ul><p>Full instructions, and answers to payment and Medicare questions, are on our <a href=\"/patients\">patient information page</a>.</p><p><em>Suitability for sedation is assessed individually. Any surgical or invasive procedure carries risks; before proceeding, you should seek a second opinion from an appropriately qualified health practitioner.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Sedation for Minor Oral Surgery",
    menuLabel: "Minor oral surgery",
    slug: "oral-surgery",
    summary: "Anaesthesia for minor oral surgery, including exposure of impacted teeth, apicectomy and frenectomy.",
    body: "<h2>A range of procedures</h2><p>Minor oral surgery covers a range of procedures, such as exposing impacted canines for orthodontic treatment, removing the tip of a tooth root (apicectomy), and releasing a tight frenum (frenectomy). Sedation helps you stay calm and comfortable, and most patients remember little of the procedure.</p><h2>Sedation or general anaesthesia</h2><p>A FANZCA specialist anaesthetist provides <a href=\"/iv-sedation\">IV sedation</a> for most patients, or <a href=\"/general-anaesthesia\">general anaesthesia</a> in clinics that meet credentialing and accreditation requirements, for more complex cases. Your anaesthetist will discuss the best option for you.</p><h2>Preparing and recovering</h2><ul><li>Fast as instructed: no food for 6 hours beforehand, and clear fluids only up to 2 hours before.</li><li>Arrange a responsible adult to take you home and stay with you for the rest of the day and night.</li><li>Do not drive, drink alcohol or sign legal documents for 24 hours afterwards.</li></ul><p>Full instructions, and answers to payment and Medicare questions, are on our <a href=\"/patients\">patient information page</a>.</p><p><em>Suitability for sedation is assessed individually. Any surgical or invasive procedure carries risks; before proceeding, you should seek a second opinion from an appropriately qualified health practitioner.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Sedation for Deep Cleaning",
    menuLabel: "Deep cleaning",
    slug: "deep-cleaning",
    summary: "Sedation for periodontal deep cleaning, for patients with sensitive gums or dental anxiety.",
    body: "<h2>The whole mouth in one visit</h2><p>Deep cleaning (periodontal debridement) removes build-up from below the gum line. For patients with sensitive gums, advanced gum disease or dental anxiety, it can be uncomfortable to sit through. Under sedation, the whole mouth can often be treated in one visit instead of several.</p><h2>Sedation for deep cleaning</h2><p>A FANZCA specialist anaesthetist provides <a href=\"/iv-sedation\">IV sedation</a> for most patients. Deep cleaning can also be combined with other treatment, such as fillings or extractions, in the same session.</p><h2>Preparing and recovering</h2><ul><li>Fast as instructed: no food for 6 hours beforehand, and clear fluids only up to 2 hours before.</li><li>Arrange a responsible adult to take you home and stay with you for the rest of the day and night.</li><li>Do not drive, drink alcohol or sign legal documents for 24 hours afterwards.</li></ul><p>Full instructions, and answers to payment and Medicare questions, are on our <a href=\"/patients\">patient information page</a>.</p><p><em>Suitability for sedation is assessed individually. Any surgical or invasive procedure carries risks; before proceeding, you should seek a second opinion from an appropriately qualified health practitioner.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Sedation for Patients with Special Needs",
    menuLabel: "Special needs",
    slug: "special-needs",
    summary: "Specialist anaesthesia for patients who find dental treatment while awake difficult.",
    body: "<h2>Care planned around you</h2><p>For people with autism, intellectual disability, or physical or sensory conditions, dental treatment while awake can be distressing or not possible. Our specialist anaesthetists work with you, your family or carers, and your dentist to plan anaesthesia around your needs. That way treatment can be done safely and with as little stress as possible, in a familiar clinic.</p><h2>Sedation or general anaesthesia</h2><p>A FANZCA specialist anaesthetist provides <a href=\"/iv-sedation\">IV sedation</a> or <a href=\"/general-anaesthesia\">general anaesthesia</a> in clinics that meet credentialing and accreditation requirements, assessed individually. A pre-anaesthetic consultation is recommended so we can plan the day with you.</p><h2>Preparing and recovering</h2><ul><li>Fast as instructed: no food for 6 hours beforehand, and clear fluids only up to 2 hours before.</li><li>Arrange a responsible adult to take you home and stay with you for the rest of the day and night.</li><li>Do not drive, drink alcohol or sign legal documents for 24 hours afterwards.</li></ul><p>Full instructions, and answers to payment and Medicare questions, are on our <a href=\"/patients\">patient information page</a>.</p><p><em>Suitability for sedation is assessed individually. Any surgical or invasive procedure carries risks; before proceeding, you should seek a second opinion from an appropriately qualified health practitioner.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Sedation for Children",
    menuLabel: "Children",
    slug: "children",
    summary: "Specialist anaesthesia for children's dental treatment, in suitable dental clinics.",
    body: "<h2>When treatment while awake isn't possible</h2><p>Some children can't manage dental treatment while awake because of their age, anxiety or the amount of work needed. We work closely with parents to make the day as calm as possible.</p><h2>Anaesthesia for children</h2><p>A FANZCA specialist anaesthetist provides <a href=\"/general-anaesthesia\">general anaesthesia</a> for children in most cases, in clinics that meet paediatric credentialing and accreditation requirements. Age and suitability are assessed individually.</p><h2>Preparing and recovering</h2><ul><li>Fast as instructed: no food for 6 hours beforehand, and clear fluids only up to 2 hours before.</li><li>Arrange a responsible adult to take you home and stay with you for the rest of the day and night.</li><li>Do not drive, drink alcohol or sign legal documents for 24 hours afterwards.</li></ul><p>Full instructions, and answers to payment and Medicare questions, are on our <a href=\"/patients\">patient information page</a>.</p><p><em>Suitability for sedation is assessed individually. Any surgical or invasive procedure carries risks; before proceeding, you should seek a second opinion from an appropriately qualified health practitioner.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
  {
    title: "Sedation for Needle Phobia and Local Anaesthetic Difficulties",
    menuLabel: "Needle phobia",
    slug: "needle-phobia",
    summary: "Anaesthesia options for patients with needle phobia or local anaesthetic that doesn't work well for them.",
    body: "<h2>When needles are the barrier</h2><p>For some people, fear of needles is the biggest barrier to dental care. Others find local anaesthetic doesn't work well for them. Your anaesthetist can use techniques to make cannula placement as comfortable as possible, and once you're sedated, local anaesthetic can be given without you being aware of it.</p><h2>Sedation or general anaesthesia</h2><p>A FANZCA specialist anaesthetist provides <a href=\"/iv-sedation\">IV sedation</a>, or <a href=\"/general-anaesthesia\">general anaesthesia</a> in clinics that meet credentialing and accreditation requirements. For patients whose local anaesthetic doesn't work well, general anaesthesia may be a better option. Your anaesthetist will discuss the best option for you.</p><h2>Preparing and recovering</h2><ul><li>Fast as instructed: no food for 6 hours beforehand, and clear fluids only up to 2 hours before.</li><li>Arrange a responsible adult to take you home and stay with you for the rest of the day and night.</li><li>Do not drive, drink alcohol or sign legal documents for 24 hours afterwards.</li></ul><p>Full instructions, and answers to payment and Medicare questions, are on our <a href=\"/patients\">patient information page</a>.</p><p><em>Suitability for sedation is assessed individually. Any surgical or invasive procedure carries risks; before proceeding, you should seek a second opinion from an appropriately qualified health practitioner.</em></p>",
    image: null,
    visibleInMenu: true,
    seoTitle: '',
    seoDescription: '',
  },
]
